### ISSUE TITLE
DNSServiceRef is not initialized

### ISSUE THREAD

**Issue by Art2B** [agnat/node_mdns#125] opened 2015-02-23 11:07 UTC
*Hello*, 

I've been through the manual installation of node mdns. I had no problem, but when I run npm test, I got the following error:

I'm running it on Ubuntu 14.04

```
> mdns@2.2.7 test /home/chacal/Projects/node_mdns
> node utils/testrun

*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>

/home/chacal/Projects/node_mdns/lib/avahi.js:21
      dns_sd.DNSServiceRefDeallocate(sr);
             ^
Error: DNSServiceRef is not initialized
    at supportsInterfaceIndexLocalOnly (/home/chacal/Projects/node_mdns/lib/avahi.js:21:14)
    at Object.<anonymous> (/home/chacal/Projects/node_mdns/lib/avahi.js:30:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/chacal/Projects/node_mdns/lib/mdns.js:31:19)
    at Module._compile (module.js:456:26)
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 
```

Is there anything I've missed or is there a real problem ?

**Comment by agnat** [comment] 2015-02-23 11:12
Probably real... unfortunately. It's caused by a recent ... uh ... fix :-/

Let me think about it for a few. To work around it either remove the offending line or just use mdns 2.2.6 for now.

Sorry 'bout that.

**Comment by Art2B** [comment] 2015-02-23 11:19
With the 2.2.6, it works. Thanks :smile: 

The crash comes from this line
https://github.com/agnat/node_mdns/commit/6444aa35e4e4e68da64c790bb01a75c98d82c258#diff-5739a57615acb5eab2833427201013d8R21

When I try a try catch on this line, it works well. What was the use of this "fix" ?

Thanks guys :+1:

**Comment by agnat** [comment] 2015-02-23 22:59
Fixed in v2.2.8.

**Closed** 2015-02-23 22:58 UTC

**Comment by agnat** [comment] 2015-02-23 23:00
> What was the use of this "fix" ?

See #123.

**Comment by achingbrain** [comment] 2015-02-24 08:05
Is there any reason why you didn't wrap [this line](https://github.com/agnat/node_mdns/blob/master/lib/avahi.js#L28) with `if (sr && sr.initialized) {` as well?  

The native code behind it [will throw](https://github.com/agnat/node_mdns/blob/0bd405332db14eb591c8be33cae8b7b795903f61/src/dns_service_ref_deallocate.cpp#L23-L25) if the service record is not initialised.

Looks like both DNSServiceRefDeallocate calls were introduced in the [same commit](https://github.com/agnat/node_mdns/commit/0ae8f2b6b97246218e90eba951d2b56a636d1d99).

**Comment by agnat** [comment] 2015-02-24 09:32
> Is there any reason why you didn't wrap this line [...] as well?

Yes. If [the call](https://github.com/agnat/node_mdns/blob/master/lib/avahi.js#L28) to `DNSServiceRegister(...)` succeeds the service record is _always_ initialized. It only matters if the call fails.

**Comment by achingbrain** [comment] 2015-02-24 10:42
My mistake - I was counting my brackets wrong..
